repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
        exclude: ^.*\/.*copy.*$
        # Explanation: ^.*\/copy\.py$ matches any file containing "copy" word in any directory.
      - id: check-yaml
        exclude: ^.*\/.*copy.*$
      - id: check-added-large-files
        exclude: ^.*\/.*copy.*$
      - id: end-of-file-fixer
        exclude: ^.*\/.*copy.*$
      - id: trailing-whitespace
        exclude: ^.*\/.*copy.*$

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.1
    hooks:
      - id: yamlfmt
        exclude: ^.*\/.*copy.*$

  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
      - id: "reorder-python-imports"
        exclude: ^.*\/.*copy.*$

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=88]
        exclude: ^.*\/.*copy.*$

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    - id: black
      language_version: python3.11
      exclude: ^.*\/.*copy\.py$
