repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
      args: [--max-line-length=88]
      exclude: ^.*\/.*copy.*$
      # Explanation: ^.*\/copy\.py$ matches any file containing "copy" word in any directory.


  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    - id: black
      language_version: python3.11
      exclude: ^.*\/.*copy.*$
